name: Weather viewer

env:
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

on:
  push:
    branches:
      - main

jobs:
    test:
      runs-on: ubuntu-latest
      name: Run tests
      services:
        postgres:
          image: postgres:15
          env:
            POSTGRES_DB: weatherviewertest
          ports:
            - 5432:5432
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Run tests
        run: mvn clean test
    deploy:
      runs-on: ubuntu-latest
      needs: test
      services:
        postgres:
          image: postgres:15
          env:
            POSTGRES_DB: weatherviewer
          ports:
            - 5432:5432
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '8'
        - name: Build using Maven
          run: mvn clean package
        - name: Upload artefact
          uses: actions/upload-artifact@v1
          with:
            name: artifact
            path: ./target/weatherviewer-1.0.0.jar