name: Weather viewer

on:
  push:
    branches:
      - main

jobs:
    test:
      runs-on: ubuntu-latest
      name: Run tests
      services:
        postgres:
          image: postgres:15
          env:
            POSTGRES_DB: weatherviewertest
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
          ports:
            - 5432:5432
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Run tests
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: mvn clean test
    deploy:
      runs-on: ubuntu-latest
      name: Deploy
      needs: test
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Set up JDK
          uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '8'
        - name: Build package
          run: mvn clean package -Dmaven.test.skip
        - name: Build Docker image
          run: docker run -t weatherviewer .
        - name: Get fly.io cli
          uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Deploy to fly.io
          run: flyctl deploy --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}