name: Weather viewer

on:
  push:
    branches:
      - main

jobs:
    test:
      runs-on: ubuntu-latest
      name: Run tests
      services:
        postgres:
          image: postgres:15
          env:
            POSTGRES_DB: weatherviewertest
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
          ports:
            - 5432:5432
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Run tests
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: mvn clean test
    deploy:
      runs-on: ubuntu-latest
      name: Deploy
      needs: test
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Set up JDK
          uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '8'
        - name: Install Vercel CLI
          run: npm install --global vercel@latest
        - name: Pull Vercel environment information
          run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        - name: Build project artifacts
          run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        - name: Deploy project artifacts
          run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --env POSTGRES_USER=${{ secrets.POSTGRES_USER }} --env POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} --env POSTGRES_URL=${{ secrets.POSTGRES_URL }}